# Generated by Django 4.0.2 on 2022-02-27 16:11

from django.db import migrations, models

from app.choices import STATES


def populate_states(apps, schema_editor):
    states = STATES                     
    State = apps.get_model('app', 'State')
    for name in states:
        obj = State(name=name)
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(populate_states),
    ]
