# Generated by Django 4.0.2 on 2022-02-27 16:28

from django.db import migrations, models
import django.db.models.deletion

from app.choices import DISTRICT_CHOICES

def create_districts(apps, *args):
    State = apps.get_model('app', 'State')
    District = apps.get_model('app', 'District')

    kl = State.objects.filter(name="Kerala").first()
    for choice in DISTRICT_CHOICES:
        d = District.objects.create(id=choice[0], state=kl, name=choice[1])
        d.save()
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.state')),
            ],
        ),
        migrations.RunPython(create_districts)
    ]
