# Generated by Django 4.0.2 on 2022-02-28 18:15

from django.db import migrations, models
import django.db.models.deletion


def create_wards(apps, *args):
    LSGBody = apps.get_model('app', 'LSGBody')
    District = apps.get_model('app', 'District')
    Ward = apps.get_model('app', 'Ward')
    ernakulam = District.objects.filter(name='Ernakulam').first()
    lsg = LSGBody.objects.create(name='Adoor Municipality',kind=10,lsg_body_code='M030100',district=ernakulam)
    lsg.save()
    ward = Ward.objects.create(name='Lorem Ipsum',number=1,lsg_body=lsg)
    ward.save()

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser_district_lsgbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('lsg_body', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.lsgbody')),
            ],
        ),
        migrations.RunPython(create_wards)
    ]
