# Generated by Django 4.0.2 on 2022-02-28 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'PHC'), (2, 'CHC')])),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please Enter a valid indian pincode', regex='^[1-9]{1}[0-9]{2}\\\\s{0, 1}[0-9]{3}$')])),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')])),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.ward')),
            ],
        ),
    ]
