# Generated by Django 4.0.2 on 2022-03-05 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_patient_expired_time_alter_patient_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.facility'),
        ),
    ]
