# Generated by Django 4.0.2 on 2022-03-05 09:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customuser_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_mobile', message='Please Enter 10/11 digit mobile number or landline as 0<std code><phone number>', regex='^((\\+91|91|0)[\\- ]{0,1})?[456789]\\d{9}$')])),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
                ('relation', models.IntegerField(choices=[(1, 'Parent'), (5, 'Grandparent'), (2, 'Spouse'), (3, 'Child'), (5, 'GrandChild'), (4, 'Sibling'), (5, 'Uncle'), (6, 'Other')])),
                ('is_primary', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.patient')),
            ],
        ),
    ]
