# Generated by Django 4.0.2 on 2022-03-05 12:07

from django.db import migrations, models



def create_seed_values(apps, *args):
    Disease = apps.get_model('app', 'Disease')
    SEED_VALUES = [
    Disease(name= "DM", icds_code= "D-32"),
    Disease(name= "Hypertension", icds_code= "HT-58"),
    Disease(name= "IHD", icds_code= "IDH-21"),
    Disease(name= "COPD", icds_code= "DPOC-144"),
    Disease(name= "Dementia", icds_code= "DM-62"),
    Disease(name= "CVA", icds_code= "CAV-89"),
    Disease(name= "Cancer", icds_code= "C-98"),
    Disease(name= "CKD", icds_code= "DC-25")
    ]
    Disease.objects.bulk_create(SEED_VALUES)

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_familydetail_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icds_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.RunPython(create_seed_values)
    ]
