# Generated by Django 4.0.2 on 2022-03-05 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_familydetail_patient_patientdisease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdisease',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
