# Generated by Django 4.0.2 on 2022-03-05 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_patientdisease_investigated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdisease',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
