# Generated by Django 4.0.2 on 2022-03-05 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_patientdisease_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[(0, 'General care'), (1, 'Genito urinary care'), (2, 'Gastro-intestinal care'), (3, 'Wound care'), (4, 'Respiratory care'), (5, 'Invasive care'), (6, 'Physiotherapy')], max_length=255)),
                ('sub_care_type', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('given_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
