# Generated by Django 4.0.2 on 2022-03-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_treatement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Treatement',
            new_name='Treatment',
        ),
    ]
