# Generated by Django 4.0.2 on 2022-03-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_treatement_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='care_type',
            field=models.IntegerField(choices=[(1, 'General care'), (2, 'Genito urinary care'), (3, 'Gastro-intestinal care'), (4, 'Wound care'), (5, 'Respiratory care'), (6, 'Invasive care'), (7, 'Physiotherapy')], max_length=255),
        ),
    ]
