# Generated by Django 4.0.2 on 2022-03-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_treatment_care_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='care_type',
            field=models.IntegerField(choices=[(1, 'General care'), (2, 'Genito urinary care'), (3, 'Gastro-intestinal care'), (4, 'Wound care'), (5, 'Respiratory care'), (6, 'Invasive care'), (7, 'Physiotherapy')]),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
