# Generated by Django 4.0.2 on 2022-03-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_treatment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='sub_care_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
