# Generated by Django 4.0.2 on 2022-03-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_visitschedule_scheduled_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palliative_phase', models.IntegerField(blank=True, choices=[(1, 'stable'), (2, 'unstable'), (3, 'deteriorating'), (4, 'terminal'), (5, 'bereavement')], null=True)),
                ('blood_pressure', models.IntegerField(blank=True, null=True)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('General_Random_Blood_Sugar', models.IntegerField(blank=True, null=True)),
                ('personal_hygiene', models.CharField(blank=True, max_length=255, null=True)),
                ('mouth_hygiene', models.CharField(blank=True, max_length=255, null=True)),
                ('pubic_hygiene', models.CharField(blank=True, max_length=255, null=True)),
                ('systemic_examination', models.CharField(blank=True, max_length=255, null=True)),
                ('patient_at_peace', models.BooleanField(default=False)),
                ('pain', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='visitschedule',
            name='visit_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.visitdetails'),
        ),
    ]
