# Generated by Django 4.0.2 on 2022-03-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_treatmentnotes_visit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitschedule',
            name='treatment_notes',
        ),
    ]
